name: 'UGF.Project.Columns'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  project:
    required: true
  column:
    required: true
  action:
    default: update
  name:
    default: ''
  position:
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'