name: 'UGF.Secrets.Update'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  type:
    default: yaml
  repo:
    required: true
  secrets:
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'