name: 'UGF.Changelog.Milestone'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  milestone:
    required: true
output:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'