name: 'UGF.Changelog.Milestone'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  milestone:
    required: true
  groups-config: 
    default: |
      [
        {
          "name": "Added",
          "labels": [
            "Feature"
          ]
        },
        {
          "name": "Changed",
          "labels": [
            "Change"
          ]
        },
        {
          "name": "Deprecated",
          "labels": [
            "Deprecation"
          ]
        },
        {
          "name": "Removed",
          "labels": [
            "Remove"
          ]
        },
        {
          "name": "Fixed",
          "labels": [
            "Bug"
          ]
        },
        {
          "name": "Security",
          "labels": [
            "Security"
          ]
        }
      ]
output:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'