name: 'UGF.Build.Parameters'
description: 'No description.'
inputs:
  config:
    default: .github/build.yml
  params:
    required: true
  type:
    default: yaml
  extract:
    default: true
  extractRegex:
    default: '(?<=Parameters(.|\n|\r)*```yaml(\n|\r))(.|\n|\r)*?(?=`)'
outputs:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'