name: 'UGF.Build.Parameters'
description: 'No description.'
inputs:
  config:
    default: .github/build.yml
  type:
    default: yaml
  extract:
    default: true
  extractRegex:
    default: '(?<=Parameters(.|\n|\r)*```yaml(\n|\r))(.|\n|\r)*?(?=`)'
  params:
    default: ''
  paramsType:
    default: yaml
  contentType:
    default: yaml
outputs:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'