name: 'UGF.Changelog.Releases'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  commit:
    default: true
  message:
    default: Update changelog
  user:
    default: GitHub Action
  email:
    default: action@github.com
  file:
    default: changelog.md
  config:
    default: .github/changelog.yml
output:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'