name: 'UGF.Changelog.Releases'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  commit:
    default: true
  message:
    default: Update changelog
  user:
    default: GitHub Action
  email:
    default: action@github.com
  file:
    default: changelog.md
  header:
    default: |
      # Changelog
      All notable changes to this project will be documented in this file.
      
      The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
      and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
  no-changelog:
    default: ' - No release notes.'
output:
  content:
    description: ''
runs:
  using: 'node12'
  main: 'dist/index.js'