name: 'UGF.Release.Update'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  id:
    description: 'Release id or tag name.'
    required: true
  tag:
    required: false
  commitish:
    required: false
  name:
    required: false
  body:
    required: false
  draft:
    required: false
  prerelease:
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'