name: 'UGF.Repository.Dispatch'
description: 'No description.'
inputs:
  token:
    default: ${{ github.token }}
  repository:
    default: ${{ github.repository }}
  eventType:
    required: true
  type:
    default: yaml
  payload:
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'